SELECT *
FROM dba_constraints
WHERE table_name='FN3PRODUCTNODE2';

SELECT *
FROM
ALL_CONS_COLUMNS
WHERE table_name='FN3PRODUCTNODE2';

SELECT *
FROM dict
WHERE table_name LIKE '%COLUMN%'


SELECT *
FROM
ALL_IND_COLUMNS
WHERE table_name='FN3ESTIMATIONSERIES';