SELECT NEWSSTAND,Max(OPERATIONDATE)
FROM FN3OPERATION
WHERE NEWSSTAND LIKE '028%'
AND NEWSSTAND IN
(SELECT NEWSSTAND FROM FN3NEWSSTANDON WHERE DATEOFF IS NULL)
GROUP BY NEWSSTAND
ORDER BY  Max(OPERATIONDATE)
