SELECT FN3PRINTINGDETAIL.DATEPRINT AS FECHA,
       FN3CODIFICATION.DISTRIBUTORROUTE AS RUTA,
       SUM(DECISION+INCREASEDEC) AS SERVICIO
FROM  FN3PRINTINGDETAIL, FN3CODIFICATION
WHERE
FN3PRINTINGDETAIL.HEADER = 'MARCA' AND
FN3PRINTINGDETAIL.PRODUCT = 'DIARIO' AND
FN3PRINTINGDETAIL.ORDERF = '1' AND
FN3PRINTINGDETAIL.DATEPRINT = TO_DATE('20020520','YYYYMMDD') AND
--FN3PRINTINGDETAIL.DATEPRINT > TO_DATE('20020519','YYYYMMDD') AND
(FN3CODIFICATION.DISTRIBUTORROUTE = 'S017' OR
FN3CODIFICATION.DISTRIBUTORROUTE = 'S019' OR
FN3CODIFICATION.DISTRIBUTORROUTE = 'S022' OR
FN3CODIFICATION.DISTRIBUTORROUTE = 'S023' OR
FN3CODIFICATION.DISTRIBUTORROUTE = 'S024' OR
FN3CODIFICATION.DISTRIBUTORROUTE = 'S025' OR
FN3CODIFICATION.DISTRIBUTORROUTE = 'S026' OR
FN3CODIFICATION.DISTRIBUTORROUTE = 'A001' OR
FN3CODIFICATION.DISTRIBUTORROUTE = 'A017' OR
FN3CODIFICATION.DISTRIBUTORROUTE = 'A018' OR
FN3CODIFICATION.DISTRIBUTORROUTE = 'A019' OR
FN3CODIFICATION.DISTRIBUTORROUTE = 'A022') AND
FN3PRINTINGDETAIL.NEWSSTAND = FN3CODIFICATION.NEWSSTAND
GROUP BY FN3CODIFICATION.DISTRIBUTORROUTE,FN3PRINTINGDETAIL.DATEPRINT;

SELECT FN3CODIFICATION.DISTRIBUTORROUTE AS RUTA, FN3NEWSSTAND.TOWN AS ZONA
FROM  FN3NEWSSTAND, FN3CODIFICATION
WHERE
(FN3CODIFICATION.DISTRIBUTORROUTE = 'S017' OR
FN3CODIFICATION.DISTRIBUTORROUTE = 'S019' OR
FN3CODIFICATION.DISTRIBUTORROUTE = 'S022' OR
FN3CODIFICATION.DISTRIBUTORROUTE = 'S023' OR
FN3CODIFICATION.DISTRIBUTORROUTE = 'S024' OR
FN3CODIFICATION.DISTRIBUTORROUTE = 'S025' OR
FN3CODIFICATION.DISTRIBUTORROUTE = 'S026' OR
FN3CODIFICATION.DISTRIBUTORROUTE = 'A001' OR
FN3CODIFICATION.DISTRIBUTORROUTE = 'A017' OR
FN3CODIFICATION.DISTRIBUTORROUTE = 'A018' OR
FN3CODIFICATION.DISTRIBUTORROUTE = 'A019' OR
FN3CODIFICATION.DISTRIBUTORROUTE = 'A022') AND
FN3NEWSSTAND.CODE = FN3CODIFICATION.NEWSSTAND
GROUP BY FN3NEWSSTAND.TOWN, FN3CODIFICATION.DISTRIBUTORROUTE;

SELECT FN3CODIFICATION.DISTRIBUTORROUTE AS RUTA
FROM  FN3CODIFICATION, FN3NEWSSTAND
WHERE (FN3NEWSSTAND.TOWN = 'GETAFE' OR
      FN3NEWSSTAND.TOWN = 'PERALES DEL RIO' OR
      FN3NEWSSTAND.TOWN = 'EL BERCIAL') AND
FN3NEWSSTAND.CODE = FN3CODIFICATION.NEWSSTAND
GROUP BY FN3CODIFICATION.DISTRIBUTORROUTE;

SELECT FN3CODIFICATION.NEWSSTAND AS PUNTODEVENTA
--       FN3CODIFICATION.DISTRIBUTORROUTE AS RUTA,
--       FN3NEWSSTAND.TOWN AS ZONA
FROM  FN3CODIFICATION, FN3NEWSSTAND
WHERE (FN3NEWSSTAND.TOWN = 'GETAFE' OR
      FN3NEWSSTAND.TOWN = 'PERALES DEL RIO' OR
      FN3NEWSSTAND.TOWN = 'EL BERCIAL') AND
FN3NEWSSTAND.CODE = FN3CODIFICATION.NEWSSTAND
ORDER BY FN3CODIFICATION.DISTRIBUTORROUTE;

SELECT FN3CODIFICATION.NEWSSTAND AS PUNTODEVENTA,
       FN3CODIFICATION.DISTRIBUTORROUTE AS RUTA,
       FN3NEWSSTAND.TOWN AS ZONA
FROM  FN3CODIFICATION,  FN3NEWSSTAND
WHERE (FN3CODIFICATION.DISTRIBUTORROUTE = 'P05S' OR
      FN3CODIFICATION.DISTRIBUTORROUTE = 'P06S' OR
      FN3CODIFICATION.DISTRIBUTORROUTE = 'P08S' OR
      FN3CODIFICATION.DISTRIBUTORROUTE = 'P11S' OR
      FN3CODIFICATION.DISTRIBUTORROUTE = 'P27S') AND
FN3NEWSSTAND.CODE = FN3CODIFICATION.NEWSSTAND
--ORDER BY FN3CODIFICATION.DISTRIBUTORROUTE
ORDER BY FN3NEWSSTAND.TOWN;

SELECT FN3PRINTINGDETAIL.DATEPRINT AS FECHA,
--       FN3CODIFICATION.DISTRIBUTORROUTE AS RUTA,
       SUM(DECISION+INCREASEDEC) AS SERVICIO
FROM  FN3PRINTINGDETAIL, FN3CODIFICATION, FN3NEWSSTAND
WHERE FN3PRINTINGDETAIL.HEADER = 'MARCA' AND
      FN3PRINTINGDETAIL.PRODUCT = 'DIARIO' AND
--      FN3PRINTINGDETAIL.ORDERF = '1' AND
--    FN3PRINTINGDETAIL.DATEPRINT = TO_DATE('20020520','YYYYMMDD') AND
      FN3PRINTINGDETAIL.DATEPRINT > TO_DATE('20020519','YYYYMMDD') AND
     (FN3NEWSSTAND.TOWN = 'GETAFE' OR
      FN3NEWSSTAND.TOWN = 'PERALES DEL RIO' OR
      FN3NEWSSTAND.TOWN = 'EL BERCIAL') AND
FN3PRINTINGDETAIL.NEWSSTAND = FN3CODIFICATION.NEWSSTAND AND
FN3NEWSSTAND.CODE = FN3CODIFICATION.NEWSSTAND AND
FN3PRINTINGDETAIL.NEWSSTAND = FN3NEWSSTAND.CODE
GROUP BY FN3PRINTINGDETAIL.DATEPRINT;
--GROUP BY FN3CODIFICATION.DISTRIBUTORROUTE,FN3PRINTINGDETAIL.DATEPRINT;



